[[plugins]] # 括弧自動補完
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]] # タグの自動補完
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xml']
hook_add = '''
    source ~/.config/nvim/plugins/vim-closetag.rc.vim
'''
